# 工作流名称
name: Build and Upload Release Asset

# 触发条件
on:
  release:
    types: [created]

# 任务
jobs:
  build-and-attach:
    # 运行环境
    runs-on: ubuntu-latest
    
    # 【重要】授予工作流写入权限
    permissions:
      contents: write

    # 任务步骤
    steps:
      # 1. 检出代码
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. 设置 QEMU
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      # 3. 设置 Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 4. 构建镜像并输出为 .tar 文件
      - name: Build Docker image and save to file
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile.alpine
          platforms: linux/arm64
          push: false
          # 【重要】将构建结果输出到这个固定的文件名
          outputs: type=docker,dest=./gost-proxy-arm64.tar
          tags: my-gost-proxy:${{ github.event.release.tag_name }}

      # 5. 【已更换】使用新工具上传镜像 .tar 文件作为 Release 的附件
      - name: Upload Release Asset
        uses: softprops/action-gh-release@v2
        with:
          # 要上传的文件列表
          files: gost-proxy-arm64.tar
