# 工作流名称
name: Build and Upload Release Asset

# 触发条件：仅当一个新的 Release 被创建时运行
on:
  release:
    types: [created]

# 任务
jobs:
  build-and-attach:
    # 运行环境
    runs-on: ubuntu-latest
    
    # ---【重要修正】授予工作流向仓库写入内容的权限 ---
    permissions:
      contents: write

    # 任务步骤
    steps:
      # 1. 检出与 Release 对应的标签的代码
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. 设置 QEMU (用于跨平台构建)
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      # 3. 设置 Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 4. 构建镜像并输出为 .tar 文件
      - name: Build Docker image and save to file
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile.alpine
          platforms: linux/arm64
          push: false
          outputs: type=docker,dest=./gost-proxy-arm64.tar
          tags: my-gost-proxy:${{ github.event.release.tag_name }}

      # 5. 上传镜像 .tar 文件作为 Release 的附件 (Asset)
      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./gost-proxy-arm64.tar
          asset_name: gost-proxy-arm64-${{ github.event.release.tag_name }}.tar
          asset_content_type: application/x-tar
